"""initial schema

Revision ID: 87472dfe8b52
Revises: 
Create Date: 2026-09-22 18:13:10.206861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from models.base import GUID


# revision identifiers, used by Alembic.
revision: str = '87472dfe8b52'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('gstin', sa.String(length=50), nullable=True),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('statutory_state', sa.String(length=100), nullable=True),
    sa.Column('lop_policy', sa.Enum('CALENDAR_DAYS', 'WORKING_DAYS', 'FIXED_30', name='lop_policy'), nullable=False),
    sa.Column('overtime_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('short_name', name=op.f('uq_companies_short_name'))
    )
    op.create_table('departments',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('manager_id', GUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_departments_company_id_companies')),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], name='fk_departments_manager_id', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('company_id', 'name', name='uq_departments_company_name')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_company_id'), ['company_id'], unique=False)

    op.create_table('designations',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_designations_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_designations')),
    sa.UniqueConstraint('company_id', 'name', name='uq_designations_company_name')
    )
    with op.batch_alter_table('designations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_designations_company_id'), ['company_id'], unique=False)

    op.create_table('devices',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('device_type', sa.Enum('FACE_PUNCH', 'FINGERPRINT', 'CARD', 'MOBILE', 'WEB', name='device_type'), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=50), nullable=True),
    sa.Column('provider', sa.Enum('ESSL', 'ORCUS', 'OTHER', name='device_provider'), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'SYNCING', 'ERROR', 'DISABLED', name='device_status'), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_devices_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('company_id', 'serial_number', name='uq_devices_company_serial')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_status'), ['status'], unique=False)

    op.create_table('essl_config',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password_encrypted', sa.Text(), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('company_short_name', sa.String(length=100), nullable=True),
    sa.Column('timeout_sec', sa.Integer(), nullable=False),
    sa.Column('sync_interval_sec', sa.Integer(), nullable=False),
    sa.Column('capabilities', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_essl_config_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_essl_config')),
    sa.UniqueConstraint('company_id', name='uq_essl_config_company')
    )
    with op.batch_alter_table('essl_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_essl_config_company_id'), ['company_id'], unique=False)

    op.create_table('holidays',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('holiday_type', sa.Enum('NATIONAL', 'STATE', 'COMPANY', 'OPTIONAL', name='holiday_type'), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_holidays_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holidays')),
    sa.UniqueConstraint('company_id', 'holiday_date', name='uq_holidays_company_date')
    )
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holidays_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_holidays_holiday_date'), ['holiday_date'], unique=False)

    op.create_table('leave_types',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('category', sa.Enum('PAID', 'UNPAID', 'SICK', 'CASUAL', 'COMPOFF', 'OTHER', name='leave_type_category'), nullable=False),
    sa.Column('days_per_year', sa.Integer(), nullable=False),
    sa.Column('carry_forward_days', sa.Integer(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_leave_types_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_types'))
    )
    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_types_company_id'), ['company_id'], unique=False)

    op.create_table('payroll_periods',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CALCULATING', 'REVIEW', 'APPROVED', 'LOCKED', name='payroll_period_status'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_payroll_periods_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll_periods')),
    sa.UniqueConstraint('company_id', 'month', 'year', name='uq_payroll_periods_company_month_year')
    )
    with op.batch_alter_table('payroll_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_periods_company_id'), ['company_id'], unique=False)

    op.create_table('salary_structures',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('payment_frequency', sa.Enum('MONTHLY', 'WEEKLY', 'HOURLY', name='salary_frequency'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('monthly_gross', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_salary_structures_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_salary_structures'))
    )
    with op.batch_alter_table('salary_structures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salary_structures_company_id'), ['company_id'], unique=False)

    op.create_table('shifts',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('grace_period_minutes', sa.Integer(), nullable=False),
    sa.Column('minimum_work_minutes', sa.Integer(), nullable=False),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.Column('overtime_enabled', sa.Boolean(), nullable=False),
    sa.Column('overtime_after_minutes', sa.Integer(), nullable=False),
    sa.Column('night_shift', sa.Boolean(), nullable=False),
    sa.Column('weekly_off_days', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_shifts_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shifts'))
    )
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shifts_company_id'), ['company_id'], unique=False)

    op.create_table('statutory_rules',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('rule_type', sa.Enum('PF', 'ESI', 'PT', 'TDS', 'OTHER', name='statutory_rule_type'), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('employee_category', sa.String(length=100), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('maximum', sa.Float(), nullable=False),
    sa.Column('calculation_method', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_statutory_rules_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statutory_rules'))
    )
    with op.batch_alter_table('statutory_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_statutory_rules_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_statutory_rules_rule_type'), ['rule_type'], unique=False)

    op.create_table('device_sync_logs',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('device_id', GUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_received', sa.Integer(), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('records_duplicate', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'PARTIAL', 'FAILED', name='sync_log_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_device_sync_logs_company_id_companies')),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_sync_logs_device_id_devices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_sync_logs'))
    )
    with op.batch_alter_table('device_sync_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_sync_logs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_sync_logs_device_id'), ['device_id'], unique=False)

    op.create_table('employees',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('resignation_date', sa.Date(), nullable=True),
    sa.Column('department_id', GUID(), nullable=True),
    sa.Column('designation_id', GUID(), nullable=True),
    sa.Column('manager_id', GUID(), nullable=True),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN', 'PROBATION', name='employment_type'), nullable=False),
    sa.Column('work_location', sa.String(length=255), nullable=True),
    sa.Column('profile_photo_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'RESIGNED', 'TERMINATED', 'ON_NOTICE', name='employee_status'), nullable=False),
    sa.Column('aadhaar_no', sa.String(length=20), nullable=True),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('ifsc', sa.String(length=20), nullable=True),
    sa.Column('account_holder_name', sa.String(length=100), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_employees_company_id_companies')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_employees_department_id_departments')),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], name=op.f('fk_employees_designation_id_designations')),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], name=op.f('fk_employees_manager_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('company_id', 'employee_code', name='uq_employees_company_code')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_designation_id'), ['designation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_employee_code'), ['employee_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_status'), ['status'], unique=False)

    op.create_table('salary_structure_components',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('salary_structure_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('component_type', sa.Enum('EARNING', 'DEDUCTION', name='salary_component_type'), nullable=False),
    sa.Column('calculation_type', sa.Enum('FIXED', 'PERCENTAGE_OF_BASIC', 'PERCENTAGE_OF_GROSS', 'FORMULA', name='calculation_type'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_salary_structure_components_company_id_companies')),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], name=op.f('fk_salary_structure_components_salary_structure_id_salary_structures')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_salary_structure_components'))
    )
    with op.batch_alter_table('salary_structure_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salary_structure_components_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_salary_structure_components_salary_structure_id'), ['salary_structure_id'], unique=False)

    op.create_table('attendance_daily',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('employee_id', GUID(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('shift_id', GUID(), nullable=True),
    sa.Column('first_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worked_minutes', sa.Integer(), nullable=False),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.Column('late_minutes', sa.Integer(), nullable=False),
    sa.Column('early_leave_minutes', sa.Integer(), nullable=False),
    sa.Column('overtime_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LEAVE', 'HOLIDAY', 'WEEKEND', 'HALF_DAY', 'MISSING_PUNCH', 'ON_DUTY', name='attendance_status'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_attendance_daily_company_id_companies')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_attendance_daily_employee_id_employees')),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_attendance_daily_shift_id_shifts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_daily')),
    sa.UniqueConstraint('company_id', 'employee_id', 'attendance_date', name='uq_attendance_daily_emp_date')
    )
    with op.batch_alter_table('attendance_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_daily_attendance_date'), ['attendance_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_daily_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_attendance_daily_company_status_date', ['company_id', 'status', 'attendance_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_daily_employee_id'), ['employee_id'], unique=False)

    op.create_table('attendance_logs',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('device_id', GUID(), nullable=True),
    sa.Column('employee_id', GUID(), nullable=True),
    sa.Column('device_user_id', sa.String(length=50), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.Enum('IN', 'OUT', 'UNKNOWN', name='event_type'), nullable=False),
    sa.Column('source', sa.Enum('ESSL', 'DEVICE', 'MANUAL', 'IMPORT', 'API', name='log_source'), nullable=False),
    sa.Column('external_event_id', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_attendance_logs_company_id_companies')),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_attendance_logs_device_id_devices')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_attendance_logs_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_logs')),
    sa.UniqueConstraint('company_id', 'idempotency_key', name='uq_attendance_logs_idempotency')
    )
    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.create_index('ix_attendance_logs_company_device_time', ['company_id', 'device_id', 'event_timestamp'], unique=False)
        batch_op.create_index('ix_attendance_logs_company_employee_time', ['company_id', 'employee_id', 'event_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_logs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_logs_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_logs_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_logs_event_timestamp'), ['event_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_logs_external_event_id'), ['external_event_id'], unique=False)

    op.create_table('employee_devices',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('employee_id', GUID(), nullable=False),
    sa.Column('device_id', GUID(), nullable=False),
    sa.Column('device_user_id', sa.String(length=50), nullable=False),
    sa.Column('face_registered', sa.Boolean(), nullable=False),
    sa.Column('fingerprint_registered', sa.Boolean(), nullable=False),
    sa.Column('sync_status', sa.Enum('PENDING', 'SYNCED', 'FAILED', 'PARTIAL', name='mapping_sync_status'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_employee_devices_company_id_companies')),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_employee_devices_device_id_devices')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_devices_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_devices')),
    sa.UniqueConstraint('company_id', 'device_id', 'device_user_id', name='uq_emp_devices_company_device_user')
    )
    with op.batch_alter_table('employee_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_devices_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_devices_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_devices_employee_id'), ['employee_id'], unique=False)

    op.create_table('employee_loans',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('employee_id', GUID(), nullable=False),
    sa.Column('loan_amount', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('installment_amount', sa.Float(), nullable=False),
    sa.Column('number_of_installments', sa.Integer(), nullable=False),
    sa.Column('paid_installments', sa.Integer(), nullable=False),
    sa.Column('outstanding_amount', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'DEFAULTED', name='loan_status'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_employee_loans_company_id_companies')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_loans_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_loans'))
    )
    with op.batch_alter_table('employee_loans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_loans_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_loans_employee_id'), ['employee_id'], unique=False)

    op.create_table('employee_salary',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('employee_id', GUID(), nullable=False),
    sa.Column('salary_structure_id', GUID(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('basic_salary', sa.Float(), nullable=False),
    sa.Column('gross_salary', sa.Float(), nullable=False),
    sa.Column('payment_frequency', sa.Enum('MONTHLY', 'WEEKLY', 'HOURLY', name='salary_frequency'), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('ifsc', sa.String(length=20), nullable=True),
    sa.Column('account_holder_name', sa.String(length=100), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_employee_salary_company_id_companies')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_salary_employee_id_employees')),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], name=op.f('fk_employee_salary_salary_structure_id_salary_structures')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_salary'))
    )
    with op.batch_alter_table('employee_salary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_salary_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_salary_employee_id'), ['employee_id'], unique=False)

    op.create_table('leave_balances',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('employee_id', GUID(), nullable=False),
    sa.Column('leave_type_id', GUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('entitled_days', sa.Float(), nullable=False),
    sa.Column('used_days', sa.Float(), nullable=False),
    sa.Column('pending_days', sa.Float(), nullable=False),
    sa.Column('remaining_days', sa.Float(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_leave_balances_company_id_companies')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_leave_balances_employee_id_employees')),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], name=op.f('fk_leave_balances_leave_type_id_leave_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_balances')),
    sa.UniqueConstraint('company_id', 'employee_id', 'leave_type_id', 'year', name='uq_leave_balances')
    )
    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_balances_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_balances_employee_id'), ['employee_id'], unique=False)

    op.create_table('payroll_records',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('payroll_period_id', GUID(), nullable=False),
    sa.Column('employee_id', GUID(), nullable=False),
    sa.Column('working_days', sa.Integer(), nullable=False),
    sa.Column('present_days', sa.Integer(), nullable=False),
    sa.Column('leave_days', sa.Float(), nullable=False),
    sa.Column('absent_days', sa.Integer(), nullable=False),
    sa.Column('lop_days', sa.Float(), nullable=False),
    sa.Column('overtime_minutes', sa.Integer(), nullable=False),
    sa.Column('gross_salary', sa.Float(), nullable=False),
    sa.Column('total_deductions', sa.Float(), nullable=False),
    sa.Column('net_salary', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CALCULATED', 'APPROVED', 'LOCKED', 'PROCESSED', name='payroll_record_status'), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_payroll_records_company_id_companies')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_payroll_records_employee_id_employees')),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], name=op.f('fk_payroll_records_payroll_period_id_payroll_periods')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll_records')),
    sa.UniqueConstraint('company_id', 'payroll_period_id', 'employee_id', name='uq_payroll_records_period_emp')
    )
    with op.batch_alter_table('payroll_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_records_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_records_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_records_payroll_period_id'), ['payroll_period_id'], unique=False)

    op.create_table('shift_assignments',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('employee_id', GUID(), nullable=False),
    sa.Column('shift_id', GUID(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_shift_assignments_company_id_companies')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_shift_assignments_employee_id_employees')),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_shift_assignments_shift_id_shifts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift_assignments'))
    )
    with op.batch_alter_table('shift_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_assignments_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_assignments_employee_id'), ['employee_id'], unique=False)

    op.create_table('users',
    sa.Column('company_id', GUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'COMPANY_ADMIN', 'HR_ADMIN', 'HR_MANAGER', 'PAYROLL_ADMIN', 'MANAGER', 'EMPLOYEE', name='role'), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('employee_id', GUID(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_users_company_id_companies')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_users_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('company_id', GUID(), nullable=True),
    sa.Column('user_id', GUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', GUID(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_audit_logs_company_id_companies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('leave_requests',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('employee_id', GUID(), nullable=False),
    sa.Column('leave_type_id', GUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leave_status'), nullable=False),
    sa.Column('reviewed_by', GUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('is_half_day', sa.Boolean(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_leave_requests_company_id_companies')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_leave_requests_employee_id_employees')),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], name=op.f('fk_leave_requests_leave_type_id_leave_types')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_leave_requests_reviewed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_requests'))
    )
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_requests_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_requests_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_requests_status'), ['status'], unique=False)

    op.create_table('loan_installments',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('loan_id', GUID(), nullable=False),
    sa.Column('installment_no', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('paid_in_payroll_period_id', GUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_loan_installments_company_id_companies')),
    sa.ForeignKeyConstraint(['loan_id'], ['employee_loans.id'], name=op.f('fk_loan_installments_loan_id_employee_loans')),
    sa.ForeignKeyConstraint(['paid_in_payroll_period_id'], ['payroll_periods.id'], name=op.f('fk_loan_installments_paid_in_payroll_period_id_payroll_periods')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loan_installments'))
    )
    with op.batch_alter_table('loan_installments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_installments_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loan_installments_loan_id'), ['loan_id'], unique=False)

    op.create_table('overtime_records',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('employee_id', GUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='overtime_status'), nullable=False),
    sa.Column('approved_by', GUID(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_overtime_records_approved_by_users')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_overtime_records_company_id_companies')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_overtime_records_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_overtime_records'))
    )
    with op.batch_alter_table('overtime_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_overtime_records_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_overtime_records_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_overtime_records_employee_id'), ['employee_id'], unique=False)

    op.create_table('payroll_components',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('payroll_record_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('component_type', sa.Enum('EARNING', 'DEDUCTION', name='payroll_component_type'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('is_statutory', sa.Boolean(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', GUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_payroll_components_company_id_companies')),
    sa.ForeignKeyConstraint(['payroll_record_id'], ['payroll_records.id'], name=op.f('fk_payroll_components_payroll_record_id_payroll_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll_components'))
    )
    with op.batch_alter_table('payroll_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_components_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_components_payroll_record_id'), ['payroll_record_id'], unique=False)

    op.create_table('payslips',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('payroll_record_id', GUID(), nullable=False),
    sa.Column('employee_id', GUID(), nullable=False),
    sa.Column('payroll_period_id', GUID(), nullable=False),
    sa.Column('gross', sa.Float(), nullable=False),
    sa.Column('total_deductions', sa.Float(), nullable=False),
    sa.Column('net', sa.Float(), nullable=False),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('GENERATED', 'DOWNLOADED', 'PRINTED', 'LOCKED', name='payslip_status'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_payslips_company_id_companies')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_payslips_employee_id_employees')),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], name=op.f('fk_payslips_payroll_period_id_payroll_periods')),
    sa.ForeignKeyConstraint(['payroll_record_id'], ['payroll_records.id'], name=op.f('fk_payslips_payroll_record_id_payroll_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payslips')),
    sa.UniqueConstraint('company_id', 'payroll_record_id', 'employee_id', name='uq_payslips_record_emp')
    )
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payslips_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payslips_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payslips_payroll_period_id'), ['payroll_period_id'], unique=False)

    op.create_table('salary_advances',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('employee_id', GUID(), nullable=False),
    sa.Column('requested_amount', sa.Float(), nullable=False),
    sa.Column('approved_amount', sa.Float(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_by', GUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deduction_installments', sa.Integer(), nullable=False),
    sa.Column('deduction_start_month', sa.String(length=7), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'APPROVED', 'PAID', 'CLOSED', 'REJECTED', name='advance_status'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_salary_advances_approved_by_users')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_salary_advances_company_id_companies')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_salary_advances_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_salary_advances'))
    )
    with op.batch_alter_table('salary_advances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salary_advances_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_salary_advances_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary_advances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salary_advances_employee_id'))
        batch_op.drop_index(batch_op.f('ix_salary_advances_company_id'))

    op.drop_table('salary_advances')
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payslips_payroll_period_id'))
        batch_op.drop_index(batch_op.f('ix_payslips_employee_id'))
        batch_op.drop_index(batch_op.f('ix_payslips_company_id'))

    op.drop_table('payslips')
    with op.batch_alter_table('payroll_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_components_payroll_record_id'))
        batch_op.drop_index(batch_op.f('ix_payroll_components_company_id'))

    op.drop_table('payroll_components')
    with op.batch_alter_table('overtime_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_overtime_records_employee_id'))
        batch_op.drop_index(batch_op.f('ix_overtime_records_date'))
        batch_op.drop_index(batch_op.f('ix_overtime_records_company_id'))

    op.drop_table('overtime_records')
    with op.batch_alter_table('loan_installments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_installments_loan_id'))
        batch_op.drop_index(batch_op.f('ix_loan_installments_company_id'))

    op.drop_table('loan_installments')
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_requests_status'))
        batch_op.drop_index(batch_op.f('ix_leave_requests_employee_id'))
        batch_op.drop_index(batch_op.f('ix_leave_requests_company_id'))

    op.drop_table('leave_requests')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_company_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_company_id'))

    op.drop_table('users')
    with op.batch_alter_table('shift_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_assignments_employee_id'))
        batch_op.drop_index(batch_op.f('ix_shift_assignments_company_id'))

    op.drop_table('shift_assignments')
    with op.batch_alter_table('payroll_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_records_payroll_period_id'))
        batch_op.drop_index(batch_op.f('ix_payroll_records_employee_id'))
        batch_op.drop_index(batch_op.f('ix_payroll_records_company_id'))

    op.drop_table('payroll_records')
    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_balances_employee_id'))
        batch_op.drop_index(batch_op.f('ix_leave_balances_company_id'))

    op.drop_table('leave_balances')
    with op.batch_alter_table('employee_salary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_salary_employee_id'))
        batch_op.drop_index(batch_op.f('ix_employee_salary_company_id'))

    op.drop_table('employee_salary')
    with op.batch_alter_table('employee_loans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_loans_employee_id'))
        batch_op.drop_index(batch_op.f('ix_employee_loans_company_id'))

    op.drop_table('employee_loans')
    with op.batch_alter_table('employee_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_devices_employee_id'))
        batch_op.drop_index(batch_op.f('ix_employee_devices_device_id'))
        batch_op.drop_index(batch_op.f('ix_employee_devices_company_id'))

    op.drop_table('employee_devices')
    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_logs_external_event_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_logs_event_timestamp'))
        batch_op.drop_index(batch_op.f('ix_attendance_logs_employee_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_logs_device_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_logs_company_id'))
        batch_op.drop_index('ix_attendance_logs_company_employee_time')
        batch_op.drop_index('ix_attendance_logs_company_device_time')

    op.drop_table('attendance_logs')
    with op.batch_alter_table('attendance_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_daily_employee_id'))
        batch_op.drop_index('ix_attendance_daily_company_status_date')
        batch_op.drop_index(batch_op.f('ix_attendance_daily_company_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_daily_attendance_date'))

    op.drop_table('attendance_daily')
    with op.batch_alter_table('salary_structure_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salary_structure_components_salary_structure_id'))
        batch_op.drop_index(batch_op.f('ix_salary_structure_components_company_id'))

    op.drop_table('salary_structure_components')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_status'))
        batch_op.drop_index(batch_op.f('ix_employees_employee_code'))
        batch_op.drop_index(batch_op.f('ix_employees_email'))
        batch_op.drop_index(batch_op.f('ix_employees_designation_id'))
        batch_op.drop_index(batch_op.f('ix_employees_department_id'))
        batch_op.drop_index(batch_op.f('ix_employees_company_id'))

    op.drop_table('employees')
    with op.batch_alter_table('device_sync_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_sync_logs_device_id'))
        batch_op.drop_index(batch_op.f('ix_device_sync_logs_company_id'))

    op.drop_table('device_sync_logs')
    with op.batch_alter_table('statutory_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statutory_rules_rule_type'))
        batch_op.drop_index(batch_op.f('ix_statutory_rules_company_id'))

    op.drop_table('statutory_rules')
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shifts_company_id'))

    op.drop_table('shifts')
    with op.batch_alter_table('salary_structures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salary_structures_company_id'))

    op.drop_table('salary_structures')
    with op.batch_alter_table('payroll_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_periods_company_id'))

    op.drop_table('payroll_periods')
    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_types_company_id'))

    op.drop_table('leave_types')
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holidays_holiday_date'))
        batch_op.drop_index(batch_op.f('ix_holidays_company_id'))

    op.drop_table('holidays')
    with op.batch_alter_table('essl_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_essl_config_company_id'))

    op.drop_table('essl_config')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_status'))
        batch_op.drop_index(batch_op.f('ix_devices_company_id'))

    op.drop_table('devices')
    with op.batch_alter_table('designations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_designations_company_id'))

    op.drop_table('designations')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_company_id'))

    op.drop_table('departments')
    op.drop_table('companies')
    # ### end Alembic commands ###
