apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: hrms
  labels:
    app.kubernetes.io/name: postgres
spec:
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - port: 5432
      targetPort: postgres
      name: postgres